/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan6_c;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.SQLException;

/**
 *
 * @author ASUS
 */
public class Movie extends javax.swing.JFrame {

    /**
     * Creates new form ListMahasiswa
     */
    Connector conn = new Connector();
    public Movie() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabelJudul = new javax.swing.JLabel();
        jTextFieldJudul = new javax.swing.JTextField();
        jLabelAlur = new javax.swing.JLabel();
        jTextFieldAlur = new javax.swing.JTextField();
        jLabelPenokohan = new javax.swing.JLabel();
        jTextFieldPenokohan = new javax.swing.JTextField();
        jLabelAkting = new javax.swing.JLabel();
        jTextFieldAkting = new javax.swing.JTextField();
        JButtonDelete = new javax.swing.JToggleButton();
        ButtonUpdate = new javax.swing.JToggleButton();
        jButtonTambah = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Judul", "Alur", "Penokohan", "Akting", "Nilai"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("List Mahasiswa");

        jLabelJudul.setText("Judul");

        jTextFieldJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJudulActionPerformed(evt);
            }
        });

        jLabelAlur.setText("Alur");

        jTextFieldAlur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlurActionPerformed(evt);
            }
        });

        jLabelPenokohan.setText("Penokohan");

        jTextFieldPenokohan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPenokohanActionPerformed(evt);
            }
        });

        jLabelAkting.setText("Akting");

        jTextFieldAkting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAktingActionPerformed(evt);
            }
        });

        JButtonDelete.setText("Delete");
        JButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonDeleteActionPerformed(evt);
            }
        });

        ButtonUpdate.setText("Update");
        ButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpdateActionPerformed(evt);
            }
        });

        jButtonTambah.setText("Tambah");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAkting)
                                    .addComponent(jLabelPenokohan)
                                    .addComponent(jLabelAlur)
                                    .addComponent(jLabelJudul))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAlur, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldPenokohan, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldAkting, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldJudul)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonTambah, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JButtonDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonClear, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelJudul)
                            .addComponent(jTextFieldJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAlur)
                            .addComponent(jTextFieldAlur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPenokohan)
                            .addComponent(jTextFieldPenokohan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAkting)
                            .addComponent(jTextFieldAkting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JButtonDelete)
                            .addComponent(jButtonTambah))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonUpdate)
                            .addComponent(jButtonClear))))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJudulActionPerformed

    private void jTextFieldAlurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlurActionPerformed

    private void jTextFieldPenokohanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPenokohanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPenokohanActionPerformed

    private void jTextFieldAktingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAktingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAktingActionPerformed
    
    private void ButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            int id = (int) jTable1.getValueAt(selectedRow, 0);
            String judul = jTextFieldJudul.getText();
            double alur = Double.parseDouble(jTextFieldAlur.getText());
            double penokohan = Double.parseDouble(jTextFieldPenokohan.getText());
            double akting = Double.parseDouble(jTextFieldAkting.getText());

            if (conn.editData(id, judul, alur, penokohan, akting)) {
                JOptionPane.showMessageDialog(this, "Data berhasil diubah.");
                loadData();
                clearForm();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu.");
        }
    }//GEN-LAST:event_ButtonUpdateActionPerformed

    private void JButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            int id = (int) jTable1.getValueAt(selectedRow, 0);
            if (conn.deleteData(id)) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
                loadData();
                clearForm();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu.");
        }
        
    }//GEN-LAST:event_JButtonDeleteActionPerformed

    private void clearForm() {
        jTextFieldJudul.setText("");
        jTextFieldAlur.setText("");
        jTextFieldPenokohan.setText("");
        jTextFieldAkting.setText("");
        jTable1.clearSelection();
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        jTextFieldJudul.setText(jTable1.getValueAt(selectedRow, 1).toString());
        jTextFieldAlur.setText(jTable1.getValueAt(selectedRow, 2).toString());
        jTextFieldPenokohan.setText(jTable1.getValueAt(selectedRow, 3).toString());
        jTextFieldAkting.setText(jTable1.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        // TODO add your handling code here:
        String Judul = jTextFieldJudul.getText();
        double Alur = Double.parseDouble(jTextFieldAlur.getText());
        double Penokohan = Double.parseDouble(jTextFieldPenokohan.getText());
        double Akting = Double.parseDouble(jTextFieldAkting.getText());
        try {
            boolean isSuccess = conn.tambahData(Judul, Alur, Penokohan, Akting);
            if (isSuccess) {
                JOptionPane.showMessageDialog(this, "Input Berhasil", "Alert", HEIGHT);
                loadData();
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Input Gagal", "Alert", HEIGHT);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal menambahkan: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_jButtonClearActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Movie().setVisible(true);
            }
        });
    }
    
    
    private void loadData() {
        try {
            conn.statement = conn.koneksi.createStatement();
            String query = "SELECT * FROM movie_db";
            ResultSet resultSet = conn.statement.executeQuery(query);

            javax.swing.table.DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel();
            tableModel.addColumn("Id");
            tableModel.addColumn("Judul");
            tableModel.addColumn("Alur");
            tableModel.addColumn("Penokohan");
            tableModel.addColumn("Akting");
            tableModel.addColumn("Nilai");

            while (resultSet.next()) {
                int id = resultSet.getInt("id");
                String Judul = resultSet.getString("Judul");
                double Alur = resultSet.getDouble("Alur");
                double Penokohan = resultSet.getDouble("Penokohan");
                double Akting = resultSet.getDouble("Akting");
                double Nilai = resultSet.getDouble("Nilai");

                tableModel.addRow(new Object[]{id, Judul, Alur, Penokohan, Akting, Nilai});
            }

            jTable1.setModel(tableModel);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ButtonUpdate;
    private javax.swing.JToggleButton JButtonDelete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAkting;
    private javax.swing.JLabel jLabelAlur;
    private javax.swing.JLabel jLabelJudul;
    private javax.swing.JLabel jLabelPenokohan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldAkting;
    private javax.swing.JTextField jTextFieldAlur;
    private javax.swing.JTextField jTextFieldJudul;
    private javax.swing.JTextField jTextFieldPenokohan;
    // End of variables declaration//GEN-END:variables
}